# Generated by Django 4.0 on 2025-06-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='geopoints',
        ),
        migrations.AddField(
            model_name='properties',
            name='location_latitude',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='location_longitude',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
