# Generated by Django 4.0 on 2025-06-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_properties_geopoints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='offering_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='price_on_application',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='property_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='license_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
