# Generated by Django 5.2 on 2025-06-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_properties_offering_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='location_latitude',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='location_longitude',
        ),
        migrations.AddField(
            model_name='properties',
            name='geopoints',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
