# Generated by Django 5.1.6 on 2025-03-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_property_featured_propertyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='amenities',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('commercial', 'Commercial'), ('loft', 'Loft'), ('studio', 'Studio'), ('villa', 'Villa'), ('townhouse', 'Townhouse'), ('penthouse', 'Penthouse'), ('duplex', 'Duplex'), ('mansion', 'Mansion'), ('farmhouse', 'Farmhouse'), ('industrial', 'Industrial'), ('office', 'Office')], max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('under_contract', 'Under Contract'), ('coming_soon', 'Coming Soon'), ('off_market', 'Off Market')], default='available', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='main.amenity'),
        ),
    ]
