# Generated by Django 4.0 on 2025-03-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_property_sale_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='properties',
            field=models.ManyToManyField(related_name='projects', to='main.Property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='main.Amenity'),
        ),
    ]
