# Generated by Django 4.0 on 2025-03-11 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_project_properties_alter_property_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFLoorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=55, null=True)),
                ('image', models.ImageField(upload_to='property_images/')),
                ('image_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.property')),
            ],
        ),
    ]
