# Generated by Django 4.0 on 2025-03-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_overviewkeysection'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location_latitude',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='location_longitude',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
