# Generated by Django 5.1.7 on 2025-03-18 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, null=True, to='main.amenity'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='main.city'),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='main.country'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='location_latitude',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='location_longitude',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('house', 'House'), ('commercial', 'Commercial'), ('loft', 'Loft'), ('studio', 'Studio'), ('villa', 'Villa'), ('townhouse', 'Townhouse'), ('penthouse', 'Penthouse'), ('duplex', 'Duplex'), ('mansion', 'Mansion'), ('farmhouse', 'Farmhouse'), ('industrial', 'Industrial'), ('office', 'Office')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('rent', 'RENT'), ('buy', 'BUY')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size in square meters', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('sold', 'Sold'), ('under_contract', 'Under Contract'), ('coming_soon', 'Coming Soon'), ('off_market', 'Off Market')], default='available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
