# Generated by Django 5.1.7 on 2025-03-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_overviewkeyblog_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='year_built',
            new_name='completion_date',
        ),
        migrations.AlterField(
            model_name='overviewkeysection',
            name='paragraph',
            field=models.TextField(max_length=455),
        ),
        migrations.AlterField(
            model_name='overviewkeysection',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
    ]
