# Generated by Django 5.1.7 on 2025-03-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_property_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overviewkeysection',
            name='paragraph',
            field=models.TextField(max_length=555),
        ),
    ]
