# Generated by Django 5.1.7 on 2025-03-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_consultationbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='youtube_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
