# Generated by Django 5.1.7 on 2025-03-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_property_youtube_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties_floors/'),
        ),
        migrations.AlterField(
            model_name='overviewkeyblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='overview_blocks/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_profileI/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='youtube_video',
            field=models.URLField(blank=True, help_text='this field is for a youtube link: eg: https://www.youtube.com/watch?v=bpTDkJxP14w', null=True),
        ),
        migrations.AlterField(
            model_name='propertyfloorplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties_floors/'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties_images/'),
        ),
    ]
