# Generated by Django 4.0 on 2025-04-29 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_team_bitrix_id_alter_property_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='main.city')),
            ],
            options={
                'unique_together': {('name', 'city')},
            },
        ),
    ]
