# Generated by Django 4.0 on 2025-05-03 13:31

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_property_sub_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='sub_city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='city', chained_model_field='city', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subcity'),
        ),
    ]
