# Generated by Django 5.0.1 on 2025-09-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_servicespageblock_paragraph_and_more'),
        ('main', '0040_delete_searchlog'),
    ]

    operations = [
    ]
