# Generated by Django 4.2.25 on 2025-10-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_featuredpropertysection_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredpropertysection',
            name='paragraph',
            field=models.TextField(max_length=1111),
        ),
    ]
