# Generated by Django 4.2.25 on 2025-10-28 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_firstparagraphsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text="Icon class (e.g., 'fa-solid fa-globe') or upload icon if using images", max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading of the section', max_length=255)),
                ('subtitle', models.TextField(help_text='Main paragraph or description')),
            ],
        ),
        migrations.DeleteModel(
            name='FirstParagraphSection',
        ),
        migrations.AddField(
            model_name='investmentfeature',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='main.investmentsection'),
        ),
    ]
