# Generated by Django 4.2.25 on 2025-11-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_blogpost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentfeature',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='investmentsection',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
