# Generated by Django 5.2.8 on 2026-03-05 08:13

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_corevalue_whowearepage_delete_whowearesection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_script_title', models.CharField(default='Our Services Includes', max_length=255)),
                ('hero_title', models.CharField(default='Services', max_length=255)),
                ('hero_paragraph', ckeditor.fields.RichTextField(default='')),
                ('translations', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Services Page',
                'verbose_name_plural': 'Services Page',
            },
        ),
        migrations.DeleteModel(
            name='ServicesSectionPageParagraph',
        ),
        migrations.AlterModelOptions(
            name='servicespageblock',
            options={'ordering': ['order'], 'verbose_name': 'Service Block', 'verbose_name_plural': 'Service Blocks'},
        ),
        migrations.AddField(
            model_name='servicespageblock',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='servicespageblock',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='servicespageblock',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main.servicespage'),
        ),
    ]
