# Generated by Django 5.2.8 on 2026-03-05 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_contactpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicesSection',
        ),
    ]
