# Generated by Django 5.1.6 on 2025-03-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_amenity_remove_property_amenities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='name')),
                ('position', models.CharField(max_length=63, verbose_name='position')),
                ('caption', models.TextField()),
                ('socials', models.TextField(default={})),
                ('phone', models.CharField(blank=True, default=None, max_length=63, null=True, verbose_name='phone')),
                ('email', models.CharField(blank=True, default=None, max_length=63, null=True, verbose_name='email')),
                ('license_no', models.TextField(default={})),
                ('picture', models.FileField(blank=True, default=None, help_text='Either set a file here', null=True, upload_to='team_images/')),
            ],
        ),
    ]
