# Generated by Django 5.1.6 on 2025-03-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_city_property_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='sale_type',
            field=models.CharField(choices=[('rent', 'RENT'), ('buy', 'BUY')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
