# Generated by Django 5.1.7 on 2025-03-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_property_amenities_alter_property_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overviewkeyblog',
            options={'ordering': ['block_position']},
        ),
        migrations.AddField(
            model_name='overviewkeyblog',
            name='block_position',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
