# Generated by Django 5.1.7 on 2025-03-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Size in square meters', max_digits=10, null=True),
        ),
    ]
