# Generated by Django 5.1.7 on 2025-03-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_consultationbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overviewkeyblog',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
