# Generated by Django 5.1.7 on 2025-04-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_blogpost_image_alter_country_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overviewkeyblog',
            name='title',
            field=models.CharField(max_length=155),
        ),
    ]
