# Generated by Django 5.1.7 on 2025-04-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_overviewkeyblog_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('branch', models.CharField(choices=[('uae', 'UAE'), ('georgia', 'Georgia')], max_length=20)),
                ('contact_way', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call')], max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
