# Generated by Django 4.0 on 2025-04-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_amenity_translations_blogpost_translations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bitrix_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, null=True, to='main.Amenity'),
        ),
    ]
