# Generated by Django 4.0 on 2025-05-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_searchlog_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
