# Generated by Django 5.0.1 on 2025-09-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_remove_property_country_remove_project_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for the reel', max_length=255)),
                ('url', models.URLField(help_text='Direct link to the Instagram reel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show this reel on the site?')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
