# Generated by Django 4.2.25 on 2026-02-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_investmentfeature_translations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespageblock',
            name='paragraph',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicessectionpageparagraph',
            name='paragraph',
            field=models.TextField(),
        ),
    ]
