# Generated by Django 5.2.8 on 2026-03-11 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_alter_servicespageblock_paragraph'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoreValue',
        ),
    ]
