# Generated by Django 4.0 on 2025-03-11 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_propertyfloorplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyfloorplan',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='main.property'),
        ),
    ]
