# Generated by Django 4.0 on 2025-03-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_propertyfloorplan_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPropertySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('paragraph', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MarketinsightSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('paragraph', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OverviewKeyBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('left', 'Left'), ('right', 'right')], max_length=100)),
                ('title', models.CharField(max_length=55)),
                ('paragraph1', models.TextField()),
                ('paragraph2', models.TextField()),
                ('image', models.ImageField(upload_to='property_images/')),
                ('image_alt', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesPageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('paragraph', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('paragraph', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesSectionPageParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('paragraph', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WhoWeAreSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('paragraph', models.TextField(max_length=555)),
            ],
        ),
    ]
