# Generated by Django 4.0 on 2025-03-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_featuredpropertysection_marketinsightsection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverviewKeySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('paragraph', models.TextField(max_length=255)),
            ],
        ),
    ]
