# Generated by Django 5.1.7 on 2025-03-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_property_bathroom_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities_description',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
