# Generated by Django 5.1.7 on 2025-03-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_overviewkeyblog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespageblock',
            name='paragraph',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicespageblock',
            name='title',
            field=models.CharField(max_length=155),
        ),
    ]
