# Generated by Django 5.0.1 on 2025-04-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_callrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
