# Generated by Django 4.0 on 2025-04-30 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_subcity'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='sub_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subcity'),
        ),
    ]
