# Generated by Django 4.0 on 2025-05-06 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_searchlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlog',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.city'),
        ),
    ]
