# Generated by Django 5.0.1 on 2025-09-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_merge_20250925_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='country',
        ),
        migrations.RemoveField(
            model_name='project',
            name='country',
        ),
        migrations.AlterUniqueTogether(
            name='subcity',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subcity',
            name='city',
        ),
        migrations.RemoveField(
            model_name='property',
            name='sub_city',
        ),
        migrations.RemoveField(
            model_name='callrequest',
            name='branch',
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='property',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicespageblock',
            name='paragraph',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servicespageblock',
            name='title',
            field=models.CharField(max_length=55),
        ),
        migrations.DeleteModel(
            name='SearchLog',
        ),
        migrations.DeleteModel(
            name='SubCity',
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
