# Generated by Django 4.2.25 on 2025-10-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_instagramreel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredpropertysection',
            name='paragraph',
            field=models.TextField(max_length=455),
        ),
    ]
