# Generated by Django 4.2.25 on 2025-10-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_featuredpropertysection_paragraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstParagraphSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('paragraph', models.TextField(max_length=255)),
                ('translations', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
