# Generated by Django 4.0 on 2025-10-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_investmentfeature_investmentsection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredpropertysection',
            name='paragraph',
            field=models.TextField(help_text='Main paragraph or description'),
        ),
    ]
