# Generated by Django 5.2.8 on 2026-02-25 13:03

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_servicespageblock_paragraph_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('value', models.CharField(max_length=255)),
                ('translations', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhoWeArePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_script_title', models.CharField(default='Expert Cross-Border Investment Consultant', max_length=255)),
                ('hero_title', models.CharField(default='Who We Are', max_length=255)),
                ('hero_paragraph', ckeditor.fields.RichTextField(default='')),
                ('mission_script_title', models.CharField(default='Vision & Mission', max_length=255)),
                ('mission_title', models.CharField(default='Our Mission', max_length=255)),
                ('mission_paragraph', ckeditor.fields.RichTextField(default='')),
                ('vision_script_title', models.CharField(default='Vision', max_length=25)),
                ('vision_title', models.CharField(default='Our Vision', max_length=255)),
                ('vision_paragraph', ckeditor.fields.RichTextField(default='')),
                ('values_script_title', models.CharField(default='Values', max_length=255)),
                ('values_title', models.CharField(default='Our Core Values', max_length=255)),
                ('translations', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Who We Are Page',
                'verbose_name_plural': 'Who We Are Page',
            },
        ),
        migrations.DeleteModel(
            name='WhoWeAreSection',
        ),
        migrations.AddField(
            model_name='corevalue',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='main.whowearepage'),
        ),
    ]
