# Generated by Django 5.2.8 on 2026-03-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_servicespage_delete_servicessectionpageparagraph_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Contact Us', max_length=255)),
                ('address', models.TextField(default='')),
                ('phone', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('whatsapp_number', models.CharField(default='', help_text='Number only, e.g. 97145477804', max_length=50)),
                ('map_embed_url', models.URLField(default='', max_length=1000)),
                ('contact_script_title', models.CharField(default='Have Questions', max_length=255)),
                ('contact_title', models.CharField(default='Get in Touch', max_length=255)),
                ('contact_paragraph', models.TextField(default='')),
                ('translations', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Page',
            },
        ),
    ]
