# Generated by Django 5.2.8 on 2026-03-07 12:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_delete_servicessection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespageblock',
            name='paragraph',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
