# Generated by Django 5.2.8 on 2026-03-11 16:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_delete_corevalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whowearepage',
            name='values_title',
        ),
        migrations.AddField(
            model_name='whowearepage',
            name='value_paragraph',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='whowearepage',
            name='values_mission_title',
            field=models.CharField(default='Our Values', max_length=255),
        ),
        migrations.AlterField(
            model_name='whowearepage',
            name='values_script_title',
            field=models.CharField(default='Vision', max_length=25),
        ),
    ]
