# Generated by Django 5.2.8 on 2026-04-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_remove_whowearepage_values_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seo',
            old_name='canonical_url',
            new_name='og_url',
        ),
        migrations.AddField(
            model_name='callrequest',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='seo',
            name='og_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seo',
            name='og_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seo',
            name='page_key',
            field=models.SlugField(blank=True, help_text="Unique key to identify this page (e.g. 'home', 'properties')", max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='seo',
            name='schema_json',
            field=models.TextField(blank=True, help_text='Raw JSON-LD schema content (without <script> tags)', null=True),
        ),
        migrations.AlterField(
            model_name='instagramreel',
            name='title',
            field=models.CharField(blank=True, help_text='Optional display title', max_length=255),
        ),
        migrations.AlterField(
            model_name='investmentfeature',
            name='icon',
            field=models.CharField(help_text="Icon class e.g. 'fa-solid fa-globe'", max_length=100),
        ),
        migrations.AlterField(
            model_name='overviewkeyblog',
            name='position',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='main.amenity'),
        ),
        migrations.AlterField(
            model_name='property',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('rent', 'Rent'), ('buy', 'Buy')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='youtube_video',
            field=models.URLField(blank=True, help_text='YouTube URL e.g. https://www.youtube.com/watch?v=xxx', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to='team_images/'),
        ),
    ]
