# Generated by Django 4.0 on 2025-06-15 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectComunityDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_detail_title', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('project_detail_sub_title', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('project_detail_description', models.TextField(blank=True, default=None, null=True)),
                ('is_features', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('project_room_infos', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('project_location_infos', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('project_price_infos', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('project_payment_plan_cunstruction', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('project_payment_plan_handover', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('project_brochur', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('project_floorplan', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('about_the_developper', models.TextField(blank=True, default=None, null=True)),
                ('project_video', models.FileField(blank=True, null=True, upload_to='')),
                ('poject_video_url', models.CharField(blank=True, max_length=150, null=True)),
                ('has_gym', models.BooleanField(default=False, verbose_name='Gym')),
                ('has_pool', models.BooleanField(default=False, verbose_name='Pool')),
                ('has_private_pool', models.BooleanField(default=False, verbose_name='Private Pool')),
                ('has_private_parking', models.BooleanField(default=False, verbose_name='Private Parking')),
                ('has_laundry', models.BooleanField(default=False, verbose_name='Laundry Facilities')),
                ('has_pet_friendly', models.BooleanField(default=False, verbose_name='Pet-Friendly')),
                ('has_elevator', models.BooleanField(default=False, verbose_name='Elevator')),
                ('has_security', models.BooleanField(default=False, verbose_name='Security')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='Balcony/Patio')),
                ('has_air_conditioning', models.BooleanField(default=False, verbose_name='Air Conditioning')),
                ('has_heating', models.BooleanField(default=False, verbose_name='Heating')),
                ('has_dishwasher', models.BooleanField(default=False, verbose_name='Dishwasher')),
                ('has_internet', models.BooleanField(default=False, verbose_name='Internet')),
                ('has_cable_tv', models.BooleanField(default=False, verbose_name='Cable TV')),
                ('has_fireplace', models.BooleanField(default=False, verbose_name='Fireplace')),
                ('has_furnished', models.BooleanField(default=False, verbose_name='Furnished')),
                ('has_wheelchair_accessible', models.BooleanField(default=False, verbose_name='Wheelchair Accessible')),
                ('has_hardwood_or_tiledfloor', models.BooleanField(default=False, verbose_name='Hardwood or Tiledfloor')),
                ('has_balcony_or_patio', models.BooleanField(default=False, verbose_name='Balcony or Patio')),
                ('has_walk_in_closet', models.BooleanField(default=False, verbose_name='Walk In Closet')),
                ('has_modern_kitchen_appliances', models.BooleanField(default=False, verbose_name='Modern Kitchen')),
                ('has_soundproofing', models.BooleanField(default=False, verbose_name='SoundProofing')),
                ('has_smart_home_features', models.BooleanField(default=False, verbose_name='SmartHome Features')),
                ('has_home_theater', models.BooleanField(default=False, verbose_name='Home theater')),
                ('has_wine_cellar', models.BooleanField(default=False, verbose_name='Wine Cellar')),
                ('has_solar_panel', models.BooleanField(default=False, verbose_name='Solar Panel')),
                ('has_eco_friendly_feature', models.BooleanField(default=False, verbose_name='eco friendly feature')),
                ('has_sauna_or_steam', models.BooleanField(default=False, verbose_name='Sauna or Steam')),
                ('has_gated_security', models.BooleanField(default=False, verbose_name='Gated Security')),
                ('has_clubhouse_or_community_center', models.BooleanField(default=False, verbose_name='Clubhouse or Community Center')),
                ('has_tennis_or_basketball', models.BooleanField(default=False, verbose_name='Tennis or basketball')),
                ('has_playground_or_park', models.BooleanField(default=False, verbose_name='PlayingGround or Park')),
                ('has_walking_or_joggin_trail', models.BooleanField(default=False, verbose_name='Walking or Jogging Trail')),
                ('has_lake_water_feature', models.BooleanField(default=False, verbose_name='Lake or Water Features')),
                ('has_golf_course', models.BooleanField(default=False, verbose_name='Golf Course')),
                ('has_restaurant_or_cafee', models.BooleanField(default=False, verbose_name='Restaurant or Cafee')),
                ('has_shuttle_or_transport_service', models.BooleanField(default=False, verbose_name='Shuttle or transport service')),
                ('has_buisness_center', models.BooleanField(default=False, verbose_name='Buisness Center')),
                ('has_community_event_or_classes', models.BooleanField(default=False, verbose_name='CommunityEvent or classes')),
                ('has_24_hours_maintenance_service', models.BooleanField(default=False, verbose_name='24 Hours Maintenance Service')),
                ('has_landscape_garden', models.BooleanField(default=False, verbose_name='Landscape Garden')),
                ('has_barbecue_or_picnic_aeas', models.BooleanField(default=False, verbose_name='Barbecue Or Picnic Areas')),
                ('has_yoga_space', models.BooleanField(default=False, verbose_name='Yoga Space')),
                ('has_on_site_storage', models.BooleanField(default=False, verbose_name='On Site Storage')),
                ('has_recycling_and_waste_service', models.BooleanField(default=False, verbose_name='Recycling And Waste services')),
                ('has_bike_storage_and_path', models.BooleanField(default=False, verbose_name='Bike Storage and Path')),
                ('has_health_or_spa_centers', models.BooleanField(default=False, verbose_name='Health or Spa Center')),
                ('main_image', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('banner_image', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('status', models.CharField(choices=[('Ready', 'Ready'), ('Offplan', 'Offplan')], default='Ready', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(null=True, upload_to='uploads/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('project_comunity_details', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='custom_project.projectcomunitydetails')),
            ],
        ),
        migrations.AddField(
            model_name='projectcomunitydetails',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_project.projects'),
        ),
    ]
